#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspnet-santuarioazureweb-20141117142239")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definizioni metodo Extensibility
  partial void OnCreated();
  partial void InsertFedPreg(FedPreg instance);
  partial void UpdateFedPreg(FedPreg instance);
  partial void DeleteFedPreg(FedPreg instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aspnet_santuarioazureweb_20141117142239ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<FedPreg> FedPreg
	{
		get
		{
			return this.GetTable<FedPreg>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FedPreg")]
public partial class FedPreg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Nome;
	
	private string _Citta;
	
	private string _Preghiera;
	
	private System.Nullable<System.DateTime> _Data;
	
	private string _Utente;
	
	private System.Nullable<bool> _Pubblica;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCittaChanging(string value);
    partial void OnCittaChanged();
    partial void OnPreghieraChanging(string value);
    partial void OnPreghieraChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnUtenteChanging(string value);
    partial void OnUtenteChanged();
    partial void OnPubblicaChanging(System.Nullable<bool> value);
    partial void OnPubblicaChanged();
    #endregion
	
	public FedPreg()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Citta", DbType="VarChar(50)")]
	public string Citta
	{
		get
		{
			return this._Citta;
		}
		set
		{
			if ((this._Citta != value))
			{
				this.OnCittaChanging(value);
				this.SendPropertyChanging();
				this._Citta = value;
				this.SendPropertyChanged("Citta");
				this.OnCittaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preghiera", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Preghiera
	{
		get
		{
			return this._Preghiera;
		}
		set
		{
			if ((this._Preghiera != value))
			{
				this.OnPreghieraChanging(value);
				this.SendPropertyChanging();
				this._Preghiera = value;
				this.SendPropertyChanged("Preghiera");
				this.OnPreghieraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date")]
	public System.Nullable<System.DateTime> Data
	{
		get
		{
			return this._Data;
		}
		set
		{
			if ((this._Data != value))
			{
				this.OnDataChanging(value);
				this.SendPropertyChanging();
				this._Data = value;
				this.SendPropertyChanged("Data");
				this.OnDataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Utente", DbType="VarChar(50)")]
	public string Utente
	{
		get
		{
			return this._Utente;
		}
		set
		{
			if ((this._Utente != value))
			{
				this.OnUtenteChanging(value);
				this.SendPropertyChanging();
				this._Utente = value;
				this.SendPropertyChanged("Utente");
				this.OnUtenteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pubblica", DbType="Bit")]
	public System.Nullable<bool> Pubblica
	{
		get
		{
			return this._Pubblica;
		}
		set
		{
			if ((this._Pubblica != value))
			{
				this.OnPubblicaChanging(value);
				this.SendPropertyChanging();
				this._Pubblica = value;
				this.SendPropertyChanged("Pubblica");
				this.OnPubblicaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
